In [1]:
f1 = y -> y ^ 3

#3 (generic function with 1 method)

In [2]:
f1(3)

27

In [3]:
using Test

In [4]:
Test.Pass

Test.Pass

In [6]:
testOne(x, y) = (
    Test.Pass

)
     

testOne (generic function with 1 method)

In [7]:
dict = Dict(:a => 1)

Dict{Symbol,Int64} with 1 entry:
  :a => 1

In [8]:
dict

Dict{Symbol,Int64} with 1 entry:
  :a => 1

In [11]:
dict[:a]

1

In [12]:
m1 = [1 1; 2 2]; m2 = [3 3]

1×2 Array{Int64,2}:
 3  3

In [22]:
m1 * transpose(m2)

2×1 Array{Int64,2}:
  6
 12

In [23]:
m2 * m1

1×2 Array{Int64,2}:
 9  9

In [24]:
m3 = [1 0; 0 1]

2×2 Array{Int64,2}:
 1  0
 0  1

In [25]:
inv(m3)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

m1 * m3

In [27]:
m1 + m3

2×2 Array{Int64,2}:
 2  1
 2  3

In [28]:
3 * m1

2×2 Array{Int64,2}:
 3  3
 6  6

In [29]:
m1 * 3

2×2 Array{Int64,2}:
 3  3
 6  6

In [30]:
m4 = [1 4; 5 3]

2×2 Array{Int64,2}:
 1  4
 5  3

In [32]:
m4i = inv(m4)

2×2 Array{Float64,2}:
 -0.176471   0.235294 
  0.294118  -0.0588235

In [33]:
m4 * m4i

2×2 Array{Float64,2}:
  1.0          0.0
 -2.22045e-16  1.0

In [34]:
m4i * m4

2×2 Array{Float64,2}:
 1.0  -1.11022e-16
 0.0   1.0        

In [36]:
m4i * m3

2×2 Array{Float64,2}:
 -0.176471   0.235294 
  0.294118  -0.0588235

In [37]:
m4i

2×2 Array{Float64,2}:
 -0.176471   0.235294 
  0.294118  -0.0588235

In [39]:
m4 ^ 2 * m4i ^ 2

2×2 Array{Float64,2}:
 1.0  -2.22045e-16
 0.0   1.0        

In [40]:
1:100

1:100

In [52]:
m6 = transpose([1:100 1:100 1:100])

3×100 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1  2  3  4  5  6  7  8  9  10  11  …  92  93  94  95  96  97  98  99  100
 1  2  3  4  5  6  7  8  9  10  11     92  93  94  95  96  97  98  99  100
 1  2  3  4  5  6  7  8  9  10  11     92  93  94  95  96  97  98  99  100

In [42]:
m6

200-element Array{Int64,1}:
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
   ⋮
  89
  90
  91
  92
  93
  94
  95
  96
  97
  98
  99
 100

In [93]:
a = [1:10_000;]

10000-element Array{Int64,1}:
     1
     2
     3
     4
     5
     6
     7
     8
     9
    10
    11
    12
    13
     ⋮
  9989
  9990
  9991
  9992
  9993
  9994
  9995
  9996
  9997
  9998
  9999
 10000

In [96]:
b = reshape(a, 100, 100)

100×100 Array{Int64,2}:
   1  101  201  301  401  501  601  …  9401  9501  9601  9701  9801   9901
   2  102  202  302  402  502  602     9402  9502  9602  9702  9802   9902
   3  103  203  303  403  503  603     9403  9503  9603  9703  9803   9903
   4  104  204  304  404  504  604     9404  9504  9604  9704  9804   9904
   5  105  205  305  405  505  605     9405  9505  9605  9705  9805   9905
   6  106  206  306  406  506  606  …  9406  9506  9606  9706  9806   9906
   7  107  207  307  407  507  607     9407  9507  9607  9707  9807   9907
   8  108  208  308  408  508  608     9408  9508  9608  9708  9808   9908
   9  109  209  309  409  509  609     9409  9509  9609  9709  9809   9909
  10  110  210  310  410  510  610     9410  9510  9610  9710  9810   9910
  11  111  211  311  411  511  611  …  9411  9511  9611  9711  9811   9911
  12  112  212  312  412  512  612     9412  9512  9612  9712  9812   9912
  13  113  213  313  413  513  613     9413  9513  9613  9713  9813   9913
 

In [97]:
b

100×100 Array{Int64,2}:
   1  101  201  301  401  501  601  …  9401  9501  9601  9701  9801   9901
   2  102  202  302  402  502  602     9402  9502  9602  9702  9802   9902
   3  103  203  303  403  503  603     9403  9503  9603  9703  9803   9903
   4  104  204  304  404  504  604     9404  9504  9604  9704  9804   9904
   5  105  205  305  405  505  605     9405  9505  9605  9705  9805   9905
   6  106  206  306  406  506  606  …  9406  9506  9606  9706  9806   9906
   7  107  207  307  407  507  607     9407  9507  9607  9707  9807   9907
   8  108  208  308  408  508  608     9408  9508  9608  9708  9808   9908
   9  109  209  309  409  509  609     9409  9509  9609  9709  9809   9909
  10  110  210  310  410  510  610     9410  9510  9610  9710  9810   9910
  11  111  211  311  411  511  611  …  9411  9511  9611  9711  9811   9911
  12  112  212  312  412  512  612     9412  9512  9612  9712  9812   9912
  13  113  213  313  413  513  613     9413  9513  9613  9713  9813   9913
 

In [102]:
b ^ 2

100×100 Array{Int64,2}:
 33335050  82845050  132355050  …  4835805050  4885315050  4934825050
 33340100  82860100  132380100     4836780100  4886300100  4935820100
 33345150  82875150  132405150     4837755150  4887285150  4936815150
 33350200  82890200  132430200     4838730200  4888270200  4937810200
 33355250  82905250  132455250     4839705250  4889255250  4938805250
 33360300  82920300  132480300  …  4840680300  4890240300  4939800300
 33365350  82935350  132505350     4841655350  4891225350  4940795350
 33370400  82950400  132530400     4842630400  4892210400  4941790400
 33375450  82965450  132555450     4843605450  4893195450  4942785450
 33380500  82980500  132580500     4844580500  4894180500  4943780500
 33385550  82995550  132605550  …  4845555550  4895165550  4944775550
 33390600  83010600  132630600     4846530600  4896150600  4945770600
 33395650  83025650  132655650     4847505650  4897135650  4946765650
        ⋮                       ⋱                                 

In [106]:
using LinearAlgebra

In [108]:
Matrix{Float64}(I, 5, 5)

5×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [109]:
using LinearAlgebra

In [113]:
eye() = (
    Matrix{Float64}(I, 5, 5)
)

eye (generic function with 1 method)

In [111]:
eye()

5×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0